# This is a basic workflow to help you get started with Actions

name: Run Tests with Groovy and Gradle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    name: Gradle Tests

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Clean and run the tests
        run: gradle clean test
        
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: "screenshots/*"  

      - name: HTML Test Report
        uses: actions/upload-artifact@v2
        with:
          name: HTML Report
          path: "build/reports/tests/test/*"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - run: aws s3 sync ./build/reports/tests/test s3://amado-demo-bucket
        name: Upload to AWS S3 Bucket
          
        
